name: 'Terraform-Azure-Windows'

on:
  push:
    paths-ignore:
      - '.devcontainer/**'
      - 'InitialNetworking/**'
      - '.github/workflows/terraform-azure-networking.yml'
      - 'LinuxAutomation/**'
      - '.github/workflows/terraform-azure-linux.yml'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - 'InitialNetworking/**'
      - 'LinuxAutomation/**'
    branches:
      - main

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ENVIRONMENT: "public"

jobs:
  infrastructure:
    name: 'Azure-Infrastructure-Windows'
    runs-on: ubuntu-latest

    env:
      TF_VAR_password: ${{ secrets.WIN_PASSWORD }}
      TF_VAR_non_prod_ou: ${{ secrets.NON_PROD_OU }}
      TF_VAR_ldapbind_account: ${{ secrets.LDAP_BIND_ACCOUNT }}
      TF_VAR_ldapbind_pw: ${{ secrets.LDAP_BIND_PASSWORD }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: WindowsAutomation/terraform-azure/

    # Validate Terraform Script
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: WindowsAutomation/terraform-azure/

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: WindowsAutomation/terraform-azure/

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: WindowsAutomation/terraform-azure/
    
    - name: Saving Plan
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN_INFRA: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
          #### Terraform Infrastructure Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`${process.env.PLAN_INFRA}\`\`\`
          
          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: WindowsAutomation/terraform-azure/

    - name: Terraform Output
      id: DevOpsPrivateIP
      if: (steps.apply.outcome == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request'
      run: terraform output DevOpsPrivateIP
      working-directory: WindowsAutomation/terraform-azure/

    # - name: Terraform Output debug
    #   id: outputdebug
    #   run: echo ${{ steps.outputwsid.outputs.stdout }}

  